after-startup-command = ['exec-and-forget sketchybar; aerospace layout h_accordion']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64'
]

# Start AeroSpace at login
start-at-login = true

accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

# ----------------------------------------------
# key bindings (windows, linux, and mac)
# ----------------------------------------------
[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-1 = 'exec-and-forget open -a /Applications/Firefox.app'
cmd-2 = 'exec-and-forget open -a /Users/jamie/Desktop/emacs/nextstep/Emacs.app'
cmd-3 = 'exec-and-forget open -a /Applications/Alacritty.app'

# NOTE meta-space default to alfred, no configuration need
# NOTE meta-tab default just works, no configuration need

alt-shift-r = 'reload-config'

# FIXME (last review: 2025-08-02) aerospace does not support that
# alt-shift-enter = floating toggle

# ----------------------------------------------
# Special Apps
# ----------------------------------------------

[[on-window-detected]]
if.app-name-regex-substring = 'wechat'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'bitwarden'
run = 'layout floating'

# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0
