* dotfiles

My personal dot files. It is recommended to *symlink* dotfiles to home folder (or whatever it should be).

** key bindings (windows, linux, and mac)

Since Gnu Emacs could almost do everthing, It's built-in browser is a true pain-in-the-ass. Therefore I decide to rely on window manager like i3 on linux, aerospace on macos, to help me switch between emacs and browser.

My definion: Command Key / Alt Key (whichever key is next to the space key) = meta
My definion: Option Key / Windows Key (whichever key is next to the meta key) = super

- meta + 1 : visit browser (firefox)
- meta + 2 : visit emacs
- meta + 3 : visit alacritty
- meta + space : application launcher (would be nicer if it can do browser search)
- meta + tab : switch applications

- super + shift + q : kill current application
- super + shift + e : exit window manager
- super + shift + r : restart/reload window manager config
- super + shift + - : minimize/hide current app
- super + shift + + : maximuze/show current app
- super + shift + enter : toggle float window and max screen

floating applications:
- wechat
- wemeetapp (tencent meeting)
- dingtalk (dingding) 

** macos apps

- hidden-bar, an ultra-light MacOS utility that helps hide menu bar icons: https://github.com/dwarvesf/hidden
- areospace, an i3-like tiling window manager for, macOS: https://github.com/nikitabobko/AeroSpace
- alfred, the ultimate launcher in macos: https://www.alfredapp.com/
- xnip, Handy Screenshot App for Mac: https://xnipapp.com/
- stat, macOS system monitor in your menu bar: https://github.com/exelban/stats

** macos key tweak

#+begin_src bash
# ubuntu
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 15
gsettings set org.gnome.desktop.peripherals.keyboard delay 200

ibus-setup # trun off emoji shortcut => which defaults to C-;

# macos
defaults write -g InitialKeyRepeat -int 15 // I think 15 is better, you can set this to 10
defaults write -g KeyRepeat -int 1
# or, config those values though GUI
open ~/Library/Preferences/.GlobalPreferences.plist
#+end_src

** setup proxy

If you use your proxy at: ~127.0.0.1:1087~

#+begin_src bash
git config --global http.proxy http://127.0.0.1:1087
git config --global --unset http.proxy

npm config set proxy http://127.0.0.1:1087
npm config delete proxy
#+end_src

#+begin_src bash
function set_proxy {
    export https_proxy=http://127.0.0.1:1087
    export http_proxy=http://127.0.0.1:1087
    export all_proxy=socks5://127.0.0.1:1081
}

function unset_proxy {
    unset https_proxy
    unset http_proxy
    unset all_proxy
}

alias et='tmux attach -t emacs-session || tmux new -s emacs-session "emacs -nw"'
alias emacs='emacs -nw'
#+end_src

