* dotfiles

My personal dot files. It is recommended to *symlink* dotfiles to home folder (or whatever it should be).

** key bindings (windows, linux, and mac)

Since Gnu Emacs could almost do everthing, It's built-in browser is a true pain-in-the-ass. Therefore I decide to rely on window manager like i3 on linux, aerospace on macos, to help me switch between emacs and browser.

My definion: Command Key / Alt Key (whichever key is next to the space key) = meta
My definion: Option Key / Windows Key (whichever key is next to the meta key) = super

- meta + 1 : switch to workspace 1
- meta + 2 : switch to workspace 2
- meta + 3 : switch to workspace 3
- meta + shift + 1 : move to workspace 1
- meta + shift + 2 : move to workspace 2
- meta + shift + 3 : move to workspace 3

- alt/opt + h : focus left
- alt/opt + j : focus down
- alt/opt + k : focus up
- alt/opt + l : focus right
- alt/opt + shift + h : move focus to left
- alt/opt + shift + j : move focus to down
- alt/opt + shift + k : move focus to up
- alt/opt + shift + l : move focus to right

- alt/opt + shift + r : reload window manager config

- meta + space : application launcher 
- meta + tab : switch applications

floating applications:
- wechat
- wemeetapp (tencent meeting)
- dingtalk (dingding) 

** linux apps

- window manager: i3blocks
- screenshot: i3blocks
- screenshot: i3blocks
- drawing: inkscape

How to use svg2tikz extension for inkscape
- https://xyz2tex.github.io/svg2tikz/install.html#installing-for-use-with-inkscape
#+begin_src bash :results verbatim :dir ~
git clone https://github.com/xyz2tex/svg2tikz
#+end_src


#+begin_src bash :results verbatim :dir ~
sudo dnf install -y i3blocks flameshot sysstat
#+end_src

** macos apps

additionally download font icons from: 
https://github.com/kvndrsslr/sketchybar-app-font/releases

#+begin_src bash
brew tap FelixKratz/formulae

brew install --cask nikitabobko/tap/aerospace
brew install --cask font-sketchybar-app-font
brew install sketchybar

brew services start sketchybar
#+end_src

** key repeat and delay tweak

#+begin_src bash
# ubuntu
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 15
gsettings set org.gnome.desktop.peripherals.keyboard delay 200

ibus-setup # trun off emoji shortcut => which defaults to C-;

# macos
defaults write -g InitialKeyRepeat -int 15 // I think 15 is better, you can set this to 10
defaults write -g KeyRepeat -int 1
# or, config those values though GUI
open ~/Library/Preferences/.GlobalPreferences.plist
#+end_src

** setup proxy

If you use your proxy at: ~127.0.0.1:1087~

#+begin_src bash
git config --global http.proxy http://127.0.0.1:1087
git config --global --unset http.proxy

npm config set proxy http://127.0.0.1:1087
npm config delete proxy
#+end_src

#+begin_src bash
export MY_PROXY=http://127.0.0.1:1087

function set-proxy() {
        export {http,https,ftp}_proxy=$MY_PROXY
        export {HTTP,HTTPS,FTP}_PROXY=$MY_PROXY
        export NO_PROXY=127.0.0.1
        git config --global http.proxy $MY_PROXY 
        git config --global https.proxy $MY_PROXY
        show-proxy
}

function unset-proxy() {
        unset {http,https,ftp}_proxy
        unset {HTTP,HTTPS,FTP}_PROXY
        unset NO_PROXY
        git config --global --unset http.proxy
        git config --global --unset https.proxy
}

function show-proxy() {
        echo "[env] http_proxy: $HTTP_PROXY"
        echo "[env] https_proxy: $HTTP_PROXY"
        echo "[env] no_proxy: $NO_PROXY"
        echo "[git] http.proxy:" $(git config --global --get http.proxy)
        echo "[git] https.proxy:" $(git config --global --get https.proxy)
}

alias et='tmux attach -t emacs-session || tmux new -s emacs-session "emacs -nw"'
alias emacs='emacs -nw'
#+end_src

#+begin_src config
Host github.com
  port 22
  User git
  HostName github.com
  PreferredAuthentications publickey
  IdentityFile ~/.ssh/id_ed25519

  # 10808 is local socks listening port number, find it in your v2ray / clash setting (through GUI, preferrably)
  ProxyCommand socat - socks5:127.0.0.1:%h:%p,socksport=10808
#+end_src

or, if you see ~Connection closed by UNKNOWN port 65535~ erros.
see: https://bannirui.github.io/2024/01/24/%E4%BB%A3%E7%90%86git%E7%9A%84ssh%E5%8D%8F%E8%AE%AE/

#+begin_src 
Host github.com
  port 443
  User git
  HostName ssh.github.com
  PreferredAuthentications publickey
  IdentityFile ~/.ssh/id_ed25519

  # 10808 is local socks listening port number, find it in your v2ray / clash setting (through GUI, preferrably)
  ProxyCommand socat - socks4:127.0.0.1:%h:%p,socksport=10808
#+end_src

** flameshot

https://github.com/flameshot-org/flameshot/issues/3326#issuecomment-2840309622

#+begin_src bash
xdotool exec flameshot gui --pin
#+end_src

** gnome shell extension

*** dash to dock

https://extensions.gnome.org/extension/307/dash-to-dock/

*** system monitor

https://extensions.gnome.org/extension/6807/system-monitor/

** setup input method to ibus

#+begin_src bash :results verbatim :dir ~
sudo dnf install ibus-rime
#+end_src

#+begin_src bash :results verbatim :dir ~
pip install PyGObject # may not necessary
ibus-setup
#+end_src

#+begin_src bash :results verbatim :dir ~
# put the following into your $HOME/.bashrc or $HOME/.zshrc or 
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
#+end_src


