[general]
# working_directory = "C:\\"

[terminal]
shell.program = 'powershell'

[env]
TERM = "xterm-256color"

[window]
padding.x = 00
padding.y = 00

# decorations = "none"
startup_mode = "Maximized"

opacity = 0.8
blur = true 

option_as_alt = "Both"

# dimensions.columns = 130
# dimensions.lines = 42
# position.x = 250
# position.y = 20

[font]
normal.family = "Maple Mono NF CN"
size = 14

[cursor]
style.blinking = "On"

[selection]
save_to_clipboard = true

[keyboard]

# For windows
bindings = [
    { key = "Slash", mods = "Control", chars = "\u001f" },
    # see: http://www.leonerd.org.uk/hacks/fixterms  /
    # \u001b = ESC (Escape)
    # [ = Control Sequence Introducer
    # 59;5u = Key/Modifier Payload
    # 59 = key code for ; (ascii 0x3B = decimal 59)
    # 5 = control with +
    { key = "Semicolon", mods = "Control", chars = "\u001b[59;5u" },
]

