local navigation = require("custom.navigation")
local map = vim.keymap.set

-- Emacs-style global editing keys. Keep mode-specific behavior explicit.
map("i", "<C-g>", "<Esc>", { desc = "Return to normal mode" })
map("c", "<C-g>", "<C-c>", { desc = "Cancel command" })
map("t", "<C-g>", "<C-\\><C-n>", { desc = "Return to normal mode" })

map({ "n", "i", "x" }, "<M-s>", navigation.save_current, { desc = "Save buffer" })
map("n", "<M-a>", "ggVG", { desc = "Select whole buffer" })
map("i", "<M-a>", "<Esc>ggVG", { desc = "Select whole buffer" })
map("x", "<M-a>", "ggVG", { desc = "Select whole buffer" })
map("n", "<M-c>", '"+y', { desc = "Copy with motion" })
map("x", "<M-c>", '"+y', { desc = "Copy selection" })
map({ "n", "x" }, "<M-v>", '"+p', { desc = "Paste after" })
map("i", "<M-v>", "<C-r>+", { desc = "Paste" })
map("n", "<M-/>", "gcc", { desc = "Toggle comment", remap = true })
map("x", "<M-/>", "gc", { desc = "Toggle comment", remap = true })

map("i", "<C-a>", "<C-o>^", { desc = "First non-blank character" })
map("i", "<C-e>", "<End>", { desc = "End of line" })
map("i", "<M-CR>", "<C-Space>", { desc = "Complete at point", remap = true })
map("i", "<M-y>", function()
	local ok, luasnip = pcall(require, "luasnip")
	if ok and luasnip.expand_or_jumpable() then
		luasnip.expand_or_jump()
	else
		vim.notify("No snippet available", vim.log.levels.INFO)
	end
end, { desc = "Expand or jump snippet" })

map({ "n", "i", "x" }, "<M-f>", function()
	require("telescope.builtin").current_buffer_fuzzy_find()
end, { desc = "Search current buffer lines" })
map("n", "<M-i>", navigation.document_symbols, { desc = "Document symbols" })
map("n", "<M-w>", function()
	require("mini.jump2d").start()
end, { desc = "Jump to visible location" })
map("n", "<M-x>", function()
	require("telescope.builtin").builtin()
end, { desc = "Run Telescope picker" })

-- Files, projects, buffers, and directories.
map("n", "<leader>.", ":edit ", { desc = "Open or create file" })
map("n", "<leader><leader>", navigation.project_files, { desc = "Find project file" })
map("n", "<leader>/", navigation.project_search, { desc = "Search project text" })
map("n", "<leader><", function()
	require("telescope.builtin").buffers()
end, { desc = "Find buffer" })
map("n", "<leader><Tab>", "<cmd>buffer #<CR>", { desc = "Last buffer" })

map("n", "<leader>bb", function()
	require("telescope.builtin").buffers()
end, { desc = "Find buffer" })
map("n", "<leader>ba", "<cmd>enew<CR>", { desc = "New buffer" })
map("n", "<leader>bn", "<cmd>enew<CR>", { desc = "New buffer" })
map("n", "<leader>bd", navigation.delete_buffer, { desc = "Delete buffer" })
map("n", "<leader>bs", navigation.save_current, { desc = "Save buffer" })
map("n", "<leader>bS", "<cmd>wall<CR>", { desc = "Save all buffers" })
map("n", "<leader>br", navigation.revert_current, { desc = "Revert buffer" })

map("n", "<leader>ff", navigation.directory_files, { desc = "Find file in directory" })
map("n", "<leader>fr", function()
	require("telescope.builtin").oldfiles()
end, { desc = "Find recent file" })
map("n", "<leader>fb", function()
	require("telescope.builtin").buffers()
end, { desc = "Find buffer" })
map("n", "<leader>fp", navigation.config_files, { desc = "Find Neovim config file" })
map("n", "<leader>pf", navigation.project_search, { desc = "Search project text" })

map("n", "<leader>od", "<cmd>Oil<CR>", { desc = "Open containing directory" })
map("n", "<leader>oD", navigation.open_external, { desc = "Reveal in system file manager" })

-- Window keys mirror the Emacs SPC w group while retaining C-w commands.
map("n", "<C-h>", "<C-w>h", { desc = "Focus left window" })
map("n", "<C-j>", "<C-w>j", { desc = "Focus lower window" })
map("n", "<C-k>", "<C-w>k", { desc = "Focus upper window" })
map("n", "<C-l>", "<C-w>l", { desc = "Focus right window" })
map("n", "<leader>wh", "<C-w>h", { desc = "Focus left window" })
map("n", "<leader>wj", "<C-w>j", { desc = "Focus lower window" })
map("n", "<leader>wk", "<C-w>k", { desc = "Focus upper window" })
map("n", "<leader>wl", "<C-w>l", { desc = "Focus right window" })
map("n", "<leader>ws", "<cmd>split<CR>", { desc = "Split below and follow" })
map("n", "<leader>wv", "<cmd>vsplit<CR>", { desc = "Split right and follow" })
map("n", "<leader>wd", "<cmd>close<CR>", { desc = "Delete window" })
map("n", "<leader>wr", "<C-w>=", { desc = "Balance windows" })
map("n", "<leader>wm", "<C-w>o", { desc = "Maximize window" })
map("n", "<leader>wR", "<cmd>redraw!<CR>", { desc = "Redraw display" })

map({ "n", "x" }, "<leader>ya", navigation.copy_reference, { desc = "Copy reference" })
map("n", "<leader>yb", navigation.copy_buffer_identifier, { desc = "Copy buffer identifier" })
map("n", "<leader>yf", navigation.copy_file_name, { desc = "Copy file name" })

-- Search/help entries retained from Kickstart, grouped for which-key.
map("n", "<leader>ht", function()
	require("telescope.builtin").help_tags()
end, { desc = "Search help" })
map("n", "<leader>hk", function()
	require("telescope.builtin").keymaps()
end, { desc = "Search keymaps" })
map("n", "<leader>hd", function()
	require("telescope.builtin").diagnostics()
end, { desc = "Search diagnostics" })
map("n", "<leader>hf", function()
	require("telescope.builtin").commands()
end, { desc = "Search commands" })
map("n", "<leader>hr", function()
	require("telescope.builtin").resume()
end, { desc = "Resume picker" })
map("n", "<leader>cx", vim.diagnostic.setloclist, { desc = "List diagnostics" })
map("n", "<leader>qq", "<cmd>confirm qall<CR>", { desc = "Quit all" })
