;;; pdf.el --- PDF viewing and continuous scrolling -*- lexical-binding: t -*-
;;; Commentary:
;; PDF Tools, wheel handling, page prefetch and viewer keys.
;; This module does not load TeX or Overleaf.  The existing +latex/roll- names
;; remain available for callers; SyncTeX integration belongs to lang/latex.el.
;;; Code:

(when (display-graphic-p)
  ;; `pdf-view-current-page' is a macro from pdf-macs.  Make it available to
  ;; the byte compiler instead of incorrectly declaring it as a function.
  (eval-when-compile
    (require 'pdf-macs))

  (declare-function pdf-cache-lookup-image "pdf-cache")
  ;; Generated by `define-pdf-cache-function', rather than a literal defun.
  (declare-function pdf-cache-number-of-pages "pdf-cache" () t)
  (declare-function pdf-cache-put-image "pdf-cache")
  (declare-function pdf-info-renderpage "pdf-info")
  (declare-function mwheel-event-window "mwheel")
  (declare-function pdf-roll-scroll-backward "pdf-roll")
  (declare-function pdf-roll-scroll-forward "pdf-roll")
  (declare-function pdf-view-desired-image-size "pdf-view"
                    (&optional page window))

  (defvar pdf-info-asynchronous)
  (defvar pdf-view-roll-minor-mode)
  (defvar pdf-view-use-scaling)

  (defvar +latex/roll-prefetch-pages 2
    "Number of nearby pages to prefetch ahead and behind in PDF roll mode.")

  (defvar +latex/roll-prefetch-max-pending 4
    "Maximum number of in-flight PDF roll page prefetch requests.")

  (defvar-local +latex/roll-prefetch-pending nil
    "In-flight PDF roll prefetch keys for the current buffer.")

  (defun +latex/roll-pre-redisplay-a (fn window)
    "Prefetch nearby pages after `pdf-roll-pre-redisplay'."
    (prog1 (funcall fn window)
      (+latex/roll-prefetch-nearby window)))

  (defun +latex/roll-event-window (event)
    "Return the live window associated with wheel EVENT."
    (let ((window (ignore-errors (mwheel-event-window event))))
      (when (framep window)
        (setq window (frame-selected-window window)))
      (and (window-live-p window) window)))

  (defun +latex/roll-event-delta (event)
    "Return vertical pixel delta from wheel EVENT, or nil."
    (or (when-let* ((delta (nth 4 event)))
          (round (cdr delta)))
        (let ((plist (nth 3 event)))
          (when (listp plist)
            (when-let* ((delta (or (plist-get plist :scrolling-delta-y)
                                   (when (plist-member plist :delta-y)
                                     (* (plist-get plist :delta-y)
                                        (frame-char-height))))))
              (round delta))))))

  (defun +latex/roll-scroll-by-pixels (delta window)
    "Scroll PDF roll WINDOW by DELTA pixels using `pdf-roll' commands."
    (unless (zerop delta)
      (with-selected-window window
        (with-current-buffer (window-buffer window)
          (if (> delta 0)
              (pdf-roll-scroll-backward delta window t)
            (pdf-roll-scroll-forward (- delta) window t))
          (+latex/roll-prefetch-nearby window)))))

  (defun +latex/roll-ultra-scroll-a (fn event &optional arg)
    "Use `pdf-roll' scrolling instead of `ultra-scroll' in PDF roll buffers."
    (let* ((window (+latex/roll-event-window event))
           (delta (+latex/roll-event-delta event)))
      (if (and window
               delta
               (with-current-buffer (window-buffer window)
                 (bound-and-true-p pdf-view-roll-minor-mode)))
          (+latex/roll-scroll-by-pixels delta window)
        (funcall fn event arg))))

  (defun +latex/roll-prefetch-candidates (page max-page)
    "Return nearby roll prefetch candidates around PAGE up to MAX-PAGE."
    (let (pages)
      (dotimes (index +latex/roll-prefetch-pages)
        (let ((offset (1+ index)))
          (when (<= (+ page offset) max-page)
            (push (+ page offset) pages))
          (when (>= (- page offset) 1)
            (push (- page offset) pages))))
      (nreverse pages)))

  (defun +latex/roll-prefetch-key (page width max-width)
    "Return the cache key used for prefetching PAGE at WIDTH/MAX-WIDTH."
    (list page width max-width))

  (defun +latex/roll-prefetch-page (page window)
    "Asynchronously prefetch PAGE for PDF roll WINDOW."
    (let* ((size (pdf-view-desired-image-size page window))
           (width (car size))
           (max-width (if pdf-view-use-scaling (* 2 width) width))
           (key (+latex/roll-prefetch-key page width max-width)))
      (unless (or (pdf-cache-lookup-image page width max-width)
                  (member key +latex/roll-prefetch-pending)
                  (>= (length +latex/roll-prefetch-pending)
                      +latex/roll-prefetch-max-pending))
        (push key +latex/roll-prefetch-pending)
        (let* ((buffer (current-buffer))
               (pdf-info-asynchronous
                (lambda (status data)
                  (when (buffer-live-p buffer)
                    (with-current-buffer buffer
                      (setq +latex/roll-prefetch-pending
                            (delete key +latex/roll-prefetch-pending))
                      (when (and (null status) data)
                        (pdf-cache-put-image page width data)))))))
          (condition-case nil
              (pdf-info-renderpage page width)
            (error
             (setq +latex/roll-prefetch-pending
                   (delete key +latex/roll-prefetch-pending))))))))

  (defun +latex/roll-prefetch-nearby (window)
    "Prefetch pages near WINDOW's current PDF roll page."
    (when (and (window-live-p window)
               (eq (window-buffer window) (current-buffer))
               (bound-and-true-p pdf-view-roll-minor-mode))
      (let* ((page (or (ignore-errors (pdf-view-current-page window)) 1))
             (page (if (integerp page) page (truncate page)))
             (max-page (pdf-cache-number-of-pages)))
        (dolist (candidate (+latex/roll-prefetch-candidates page max-page))
          (+latex/roll-prefetch-page candidate window)))))

  (defun +latex/roll-setup ()
    "Enable continuous PDF scrolling with trackpad-friendly wheel handling."
    (pdf-view-roll-minor-mode 1)
    (setq-local mouse-wheel-scroll-amount '(5 ((shift) . 1)))
    (setq-local mouse-wheel-progressive-speed nil)
    (when (local-variable-p 'pixel-scroll-precision-mode)
      (kill-local-variable 'pixel-scroll-precision-mode))
    (when (boundp 'mwheel-coalesce-scroll-events)
      (setq-local mwheel-coalesce-scroll-events nil))
    (+latex/roll-prefetch-nearby (selected-window)))

  (use-package pdf-tools
    :ensure t
    :if (not (eq system-type 'windows-nt))
    :mode ("\\.[pP][dD][fF]\\'" . pdf-view-mode)
    :magic ("%PDF" . pdf-view-mode)
    :hook
    (pdf-view-mode . +latex/roll-setup)
    :custom
    (pdf-view-use-scaling nil)
    :init
    (pdf-tools-install)
    :config
    (with-eval-after-load 'pdf-roll
      (when (advice-member-p #'+latex/roll-ultra-scroll-a
                             'pdf-roll-pre-redisplay)
        (advice-remove 'pdf-roll-pre-redisplay
                       #'+latex/roll-ultra-scroll-a))
      (unless (advice-member-p #'+latex/roll-pre-redisplay-a
                               'pdf-roll-pre-redisplay)
        (advice-add 'pdf-roll-pre-redisplay :around
                    #'+latex/roll-pre-redisplay-a)))

    (with-eval-after-load 'ultra-scroll
      (when (fboundp 'ultra-scroll)
        (unless (advice-member-p #'+latex/roll-ultra-scroll-a
                                 'ultra-scroll)
          (advice-add 'ultra-scroll :around
                      #'+latex/roll-ultra-scroll-a)))
      (when (fboundp 'ultra-scroll-mac)
        (unless (advice-member-p #'+latex/roll-ultra-scroll-a
                                 'ultra-scroll-mac)
          (advice-add 'ultra-scroll-mac :around
                      #'+latex/roll-ultra-scroll-a))))

    (general-define-key
     :keymaps 'pdf-view-mode-map
     :states '(normal visual motion)
     "-" #'ignore
     "=" #'ignore)

    (evil-define-key* '(normal visual motion) pdf-view-mode-map
      (kbd "C-d") #'pdf-view-next-page-command
      (kbd "C-u") #'pdf-view-previous-page-command)))

(provide 'init-pdf)
;;; pdf.el ends here
