wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/images/wallpaper-2.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/.config/hypr/images/wallpaper-2.png
    fit_mode = cover
}
