# [general]
# working_directory = "$HOME"

# [terminal.shell]
# program = "/bin/bash"

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

# decorations = "none"
startup_mode = "Maximized"

opacity = 1
blur = true 

option_as_alt = "Both"

[font]
normal.family = "Maple Mono NF CN"
size = 18

[cursor]
style.blinking = "On"

[terminal]

[keyboard]

# For Mac
bindings = [
    { key = "Slash", mods = "Control", chars = "\u001f" },
    # see: http://www.leonerd.org.uk/hacks/fixterms  /
    # \u001b = ESC (Escape)
    # [ = Control Sequence Introducer
    # 59;5u = Key/Modifier Payload
    # 59 = key code for ; (ascii 0x3B = decimal 59)
    # 5 = control with +
    { key = "Semicolon", mods = "Control", chars = "\u001b[59;5u" },
]
